image = "/capstor/scratch/cscs/ahernnde/container-image/openfold/ngc-openfold-24.03.sqsh"

mounts = [
  "/capstor:/capstor",
  "/etc/slurm:/etc/slurm",
  "/users/ahernnde:/users/ahernnde"
]

writable = true

workdir = "/users/ahernnde/project/repos/mlcommons-hpc/openfold"

[annotations]
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "cuda12"

[env]
NCCL_DEBUG = "INFO"
