image = "/capstor/scratch/cscs/lukasd/images/rocm-cosmoflow+6.3.3-tf2.15.sqsh"

mounts = [
  "/capstor/scratch/cscs",
  "/iopsstor/scratch/cscs",
  "/etc/slurm",
  #"/users/$USER/x86_64",
  #"/users/$USER/.wget-hsts",
  #"/users/$USER/.bash_history",
]

writable = true

[annotations]
#com.hooks.cxi.enabled = "true"
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "rocm6"

[env]
HOROVOD_LOG_LEVEL = "INFO"
NCCL_DEBUG = "INFO"
