#!/bin/bash
#
# Copyright 2023 NVIDIA CORPORATION
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Usage: sbatch scripts/multi_node_training.sub

#SBATCH --job-name mlperf-openfold
#SBATCH --time 02:15:00
#SBATCH --nodes 16
#SBATCH --ntasks-per-node 4
#SBATCH --output logs/slurm-%x-%j.out

set -euo pipefail

export SLURM_CPU_BIND="verbose"

if nvidia-smi &> /dev/null; then
    export SLURM_GPUS_PER_TASK=1
    export SLURM_CPUS_PER_TASK=72
    CE_ENV_TOML="env/ngc-openfold-24.03.toml"
elif rocm-smi &> /dev/null; then
    export SLURM_CPUS_PER_TASK=24
    # CE_ENV_TOML="env/rocm-openfold-6.3.3-pt2.4.0.toml"
    : "${CE_ENV_TOML="env/rocm-openfold+6.4.4-2.7.1.toml"}"
else
    echo "Error: No CPU-only environment available."
fi

. $SLURM_SUBMIT_DIR/../utils/all_ce.sh


mlc_utils_set_enroot_entrypoint

# Print current datetime:
echo "START" $(date +"%Y-%m-%d %H:%M:%S")

# Print node list:
echo "SLURM_JOB_ID=$SLURM_JOB_ID"
echo "SLURM_JOB_NUM_NODES=$SLURM_JOB_NUM_NODES"
echo "SLURM_NODELIST=$SLURM_NODELIST"

# Note: the following srun commands assume that pyxis plugin is installed on a SLURM cluster.
# https://github.com/NVIDIA/pyxis

# Download container and give it a name:
srun \
--container-workdir=$(pwd) --environment="$(realpath ${CE_ENV_TOML})" \
bash -c 'echo "srun SLURM_JOB_ID=$SLURM_JOB_ID SLURMD_NODENAME=$SLURMD_NODENAME"'

export BASE_DATA_DIR="/iopsstor/scratch/cscs/lukasd/ds/mlperf/data/openfold/pdb_data"
export TRAINING_RUN_DIR="$(pwd)"


while [[ $# -gt 0 ]]; do
    case $1 in
        --n-epochs)
            max_epochs=$2
            shift 2
            ;;
        --n-train)
            n_train=$2
            shift 2
            ;;
        --n-valid)
            n_valid=$2
            shift 2
            ;;
        --wandb)
            enable_wandb=1
            shift 1
            ;;
        *)
            break
            ;;
    esac
done

: ${local_batch_size:=1}
: ${num_train_iters:=2000}
: ${val_every_iters:=40}

if [ ! -z ${max_epochs+x} ] || [ ! -z ${n_train+x} ]; then  # max_epochs or n_train is set
    : ${max_epochs:=50}
    : ${n_train:=$(( 40*16 ))}

    echo "Using modified training data settings configured from command line."
    set -x
    global_batch_size=$(( ${local_batch_size} * ${SLURM_NTASKS} ))
    val_every_iters=$(( ${n_train} / ${global_batch_size} ))
    num_train_iters=$(( ${max_epochs} * ${val_every_iters} ))
    set +x
fi

# Print current datetime again:
echo "READY" $(date +"%Y-%m-%d %H:%M:%S")

# Set number of threads to use for parallel regions:
export OMP_NUM_THREADS=1

# Set MLPerf variables:
export DATESTAMP=$(date +"%y%m%d%H%M%S%N")
export EXP_ID=1

export MASTER_ADDR=$(hostname)
export MASTER_PORT=29500


mlc_utils_srun_disp_gpu_mem
trap mlc_utils_sbatch_disp_gpu_mem TERM EXIT KILL
mlc_utils_srun_dmesg_bg

# Run the command:
set -x
srun -ul \
--container-workdir=$(pwd) --environment="$(realpath ${CE_ENV_TOML})" \
${SRUN_EXTRA_ARGS:-} ${ENROOT_ENTRYPOINT:-} \
bash -c \
"
hostname
export SLURM_NTASKS_PER_NODE=\${SLURM_TASKS_PER_NODE%%(*}
set -x
RANK=\$SLURM_PROCID \
WORLD_SIZE=\$SLURM_NTASKS \
LOCAL_RANK=\$SLURM_LOCALID \
LOCAL_WORLD_SIZE=\$SLURM_NTASKS_PER_NODE \
python train.py \
--training_dirpath ${TRAINING_RUN_DIR} \
--pdb_mmcif_chains_filepath ${BASE_DATA_DIR}/pdb_mmcif/processed/chains.csv \
--pdb_mmcif_dicts_dirpath ${BASE_DATA_DIR}/pdb_mmcif/processed/dicts \
--pdb_obsolete_filepath ${BASE_DATA_DIR}/pdb_mmcif/processed/obsolete.dat \
--pdb_alignments_dirpath ${BASE_DATA_DIR}/open_protein_set/processed/pdb_alignments \
--initialize_parameters_from ${BASE_DATA_DIR}/mlperf_hpc_openfold_resumable_checkpoint.pt \
--seed 1234567890 \
--num_train_iters ${num_train_iters} \
--val_every_iters ${val_every_iters} \
--local_batch_size ${local_batch_size} \
--base_lr 1e-3 \
--warmup_lr_init 1e-5 \
--warmup_lr_iters 0 \
--num_train_dataloader_workers 14 \
--num_val_dataloader_workers 2 \
--distributed \
${n_valid+--n_valid ${n_valid}} \
${enable_wandb+--wandb}"

set +x
mlc_utils_srun_disp_gpu_mem
mlc_utils_kill_dmesg_bg