image = "/capstor/scratch/cscs/lukasd/images/ngc-open_catalyst+24.03.sqsh"

mounts = [
  "/capstor/scratch/cscs",
  "/iopsstor/scratch/cscs",
  "/etc/slurm",
  "/users/$USER/.vscode-server",
  "/users/$USER/.wget-hsts",
  "/users/$USER/.bash_history",
]

writable = true

[annotations]
#com.hooks.cxi.enabled = "true"
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "cuda12"

[env]
#TORCH_CPP_LOG_LEVEL = "INFO"
#TORCH_DISTRIBUTED_DEBUG = "DETAIL"
#TORCH_NCCL_BLOCKING_WAIT = "1"
#NCCL_ASYNC_ERROR_HANDLING = "1"
NCCL_DEBUG = "INFO"
