image = "/capstor/scratch/cscs/lukasd/images/rocm-deepcam+6.3.3-pt2.4.0.sqsh"

mounts = [
  "/capstor/scratch/cscs",
  "/iopsstor/scratch/cscs",
  "/etc/slurm",
  "/users/${USER}/x86_64",
  "/users/${USER}/.wget-hsts",
  "/users/${USER}/.bash_history",
]

writable = true

[annotations]
#com.hooks.cxi.enabled = "true"
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "rocm6"

[env]
NCCL_DEBUG = "INFO"
